server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    absolute_redirect off;

    location = / {
        return 404;
    }

    location = /nlp/prediksi-berita {
        return 301 /nlp/prediksi-berita/;
    }

    location ^~ /nlp/prediksi-berita/ {
        try_files $uri $uri/ /nlp/prediksi-berita/index.html;
    }

    location / {
        return 404;
    }
}