upstream prediksi_berita_web {
    server prediksi-berita-web:3000;
}

upstream prediksi_berita_api {
    server prediksi-berita-api:8000;
}

server {
    listen 80;
    server_name _;

    location = /nlp/prediksi-berita {
        return 301 /nlp/prediksi-berita/;
    }

    location ^~ /nlp/prediksi-berita/api/ {
        proxy_pass http://prediksi_berita_api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 10M;
    }

    location ^~ /nlp/prediksi-berita/ {
        proxy_pass http://prediksi_berita_web/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}